package org.jahia.modules.upa.mfa.totp;

import org.junit.After;
import org.junit.Assume;
import org.junit.Test;

import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;
import java.util.Base64;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * F16 / D2 (key-source sub-gap): the TOTP encryption key is resolved from the operator config
 * ({@code secret.encryption.key}) when present, else an auto-generated per-install key file under
 * {@code <jahiaVarDir>/mfa-factors/secret.key} — and is <b>never a compiled-in constant</b>. The
 * cipher round-trip / envelope / tamper cases are already covered by {@link TotpSecretCipherTest};
 * this suite locks the <i>key resolution</i> order and the not-hardcoded property.
 * <p>
 * No Mockito is available in this module; the auto-file path is exercised by pointing Jahia's
 * {@code SettingsBean} singleton at a temp var directory via reflection (restored after each test).
 */
public class TotpSecretKeySourceTest {

    private static final String CONFIG_KEY = "secret.encryption.key";

    private Object previousSettingsBean;
    private boolean settingsBeanSwapped;

    @After
    public void restoreSettingsBean() throws Exception {
        if (settingsBeanSwapped) {
            setSettingsBeanInstance(previousSettingsBean);
            settingsBeanSwapped = false;
        }
    }

    // --- config key precedence + load-bearing (never a shared hardcoded key) --------------------

    @Test
    public void configuredKeyRoundTrips() {
        TotpSecretCipher cipher = new TotpSecretCipher();
        cipher.activate(Collections.singletonMap(CONFIG_KEY, base64Key((byte) 0x2A)));
        String enc = cipher.encrypt("JBSWY3DPEHPK3PXP");
        assertEquals("JBSWY3DPEHPK3PXP", cipher.decrypt(enc));
    }

    @Test
    public void configuredKeyIsLoadBearing_aDifferentKeyCannotDecrypt() {
        // Two ciphers configured with DIFFERENT operator keys must be cryptographically isolated:
        // ciphertext from key A cannot be decrypted with key B. If the key were a compiled-in
        // constant (ignored config), B would decrypt A's ciphertext — this test would then fail.
        TotpSecretCipher cipherA = new TotpSecretCipher();
        cipherA.activate(Collections.singletonMap(CONFIG_KEY, base64Key((byte) 0x00)));
        TotpSecretCipher cipherB = new TotpSecretCipher();
        cipherB.activate(Collections.singletonMap(CONFIG_KEY, base64Key((byte) 0x01)));

        String encryptedWithA = cipherA.encrypt("JBSWY3DPEHPK3PXP");
        assertNotEquals(base64Key((byte) 0x00), base64Key((byte) 0x01));
        try {
            cipherB.decrypt(encryptedWithA);
            fail("a cipher with a DIFFERENT configured key must not decrypt A's ciphertext "
                    + "(proves the operator key is actually used, not a hardcoded constant)");
        } catch (IllegalStateException expected) {
            // GCM auth-tag failure under the wrong key
        }
    }

    // --- auto-generated key file when no config key ---------------------------------------------

    @Test
    public void noConfigKey_generatesOwnerOnlyKeyFileUnderVarDir() throws Exception {
        Path varDir = pointSettingsBeanAtTempVarDir();
        TotpSecretCipher cipher = new TotpSecretCipher();
        cipher.activate(emptyProps());

        Path keyFile = varDir.resolve("mfa-factors/secret.key");
        assertTrue("an auto key file must be created under <varDir>/mfa-factors/secret.key",
                Files.exists(keyFile));
        String enc = cipher.encrypt("JBSWY3DPEHPK3PXP");
        assertEquals("the auto-generated key must encrypt/decrypt round-trip",
                "JBSWY3DPEHPK3PXP", cipher.decrypt(enc));

        try {
            Set<PosixFilePermission> perms = Files.getPosixFilePermissions(keyFile);
            assertFalse("key file must not be group-readable", perms.contains(PosixFilePermission.GROUP_READ));
            assertFalse("key file must not be world-readable", perms.contains(PosixFilePermission.OTHERS_READ));
        } catch (UnsupportedOperationException nonPosix) {
            // Non-POSIX filesystem — permission restriction is best-effort there.
        }
    }

    @Test
    public void autoGeneratedKeyIsRandomPerInstall_notHardcoded() throws Exception {
        // Two fresh installs (distinct empty var dirs) must generate DIFFERENT keys, so ciphertext
        // from one is undecryptable by the other. A compiled-in constant would make them identical.
        Path varDir1 = pointSettingsBeanAtTempVarDir();
        TotpSecretCipher cipher1 = new TotpSecretCipher();
        cipher1.activate(emptyProps());
        String encFrom1 = cipher1.encrypt("JBSWY3DPEHPK3PXP");

        pointSettingsBeanAtTempVarDir(); // a second, independent install
        TotpSecretCipher cipher2 = new TotpSecretCipher();
        cipher2.activate(emptyProps());

        assertTrue("sanity: first install created its key file", Files.exists(varDir1.resolve("mfa-factors/secret.key")));
        try {
            cipher2.decrypt(encFrom1);
            fail("a second install's auto-generated key must not decrypt the first install's "
                    + "ciphertext (keys are per-install random, never a compiled-in constant)");
        } catch (IllegalStateException expected) {
            // expected — independent random keys
        }
    }

    @Test
    public void blankConfigKey_fallsBackToKeyFile() throws Exception {
        Path varDir = pointSettingsBeanAtTempVarDir();
        TotpSecretCipher cipher = new TotpSecretCipher();
        Map<String, Object> props = new HashMap<>();
        props.put(CONFIG_KEY, "   "); // blank → not a valid operator key → fall back to the file
        cipher.activate(props);
        assertTrue("a blank config key must fall back to the auto key file",
                Files.exists(varDir.resolve("mfa-factors/secret.key")));
        assertEquals("JBSWY3DPEHPK3PXP", cipher.decrypt(cipher.encrypt("JBSWY3DPEHPK3PXP")));
    }

    // --- static source-scan: no hardcoded key literal -------------------------------------------

    @Test
    public void source_containsNoHardcodedKeyLiteral() throws Exception {
        Path source = Paths.get("src/main/java/org/jahia/modules/upa/mfa/totp/TotpSecretCipher.java");
        Assume.assumeTrue("source scan skipped (not run from the module dir)", Files.exists(source));
        String code = new String(Files.readAllBytes(source), StandardCharsets.UTF_8);

        // The key must be sourced dynamically, not embedded: config property + KeyGenerator present.
        assertTrue("key must be resolvable from the operator config property", code.contains(CONFIG_KEY));
        assertTrue("an auto key must be generated with KeyGenerator", code.contains("KeyGenerator"));

        // No string literal long enough to be a base64-encoded 256-bit key should appear in source.
        Matcher m = Pattern.compile("\"([A-Za-z0-9+/=_-]{40,})\"").matcher(code);
        while (m.find()) {
            String literal = m.group(1);
            try {
                byte[] decoded = Base64.getDecoder().decode(literal);
                if (decoded.length >= 16) {
                    fail("suspicious base64 literal in source that decodes to " + decoded.length
                            + " bytes — a hardcoded key must never be embedded: " + literal);
                }
            } catch (IllegalArgumentException notBase64) {
                // not base64 — harmless
            }
        }
    }

    // --- helpers --------------------------------------------------------------------------------

    private static String base64Key(byte fill) {
        byte[] raw = new byte[32];
        java.util.Arrays.fill(raw, fill);
        return Base64.getEncoder().encodeToString(raw);
    }

    private static Map<String, Object> emptyProps() {
        return new HashMap<>();
    }

    /** Point SettingsBean at a fresh temp var dir; returns the dir. Restored in {@link #restoreSettingsBean()}. */
    private Path pointSettingsBeanAtTempVarDir() throws Exception {
        Path varDir = Files.createTempDirectory("mfa-totp-var");
        varDir.toFile().deleteOnExit();
        Object stub = allocateSettingsBeanWithVarDir(varDir.toAbsolutePath().toString());
        if (!settingsBeanSwapped) {
            previousSettingsBean = getSettingsBeanInstance();
            settingsBeanSwapped = true;
        }
        setSettingsBeanInstance(stub);
        return varDir;
    }

    private static Object allocateSettingsBeanWithVarDir(String varDir) throws Exception {
        Class<?> sb = Class.forName("org.jahia.settings.SettingsBean");
        Object instance = unsafe().allocateInstance(sb); // skip the heavy constructor
        Field varField = sb.getDeclaredField("jahiaVarDiskPath");
        varField.setAccessible(true);
        varField.set(instance, varDir);
        return instance;
    }

    private static Object getSettingsBeanInstance() throws Exception {
        Class<?> sb = Class.forName("org.jahia.settings.SettingsBean");
        Field f = sb.getDeclaredField("instance");
        f.setAccessible(true);
        return f.get(null);
    }

    private static void setSettingsBeanInstance(Object value) throws Exception {
        Class<?> sb = Class.forName("org.jahia.settings.SettingsBean");
        Field f = sb.getDeclaredField("instance");
        f.setAccessible(true);
        f.set(null, value);
    }

    private static sun.misc.Unsafe unsafe() throws Exception {
        Field theUnsafe = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
        theUnsafe.setAccessible(true);
        return (sun.misc.Unsafe) theUnsafe.get(null);
    }
}
